apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywar
  template:
    metadata:
      labels:
        app: mywar
    spec:
      containers:
      - name: mywar-container
        image: mywarapp
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
